-- ============================================================
-- Lynks Opportunities Seed Data
-- Real, verified opportunities for Caribbean youth
-- Run this in Supabase SQL Editor
-- ============================================================

INSERT INTO opportunities (id, title, company, location, pay, url, age_requirement, experience_required, category, description, salary_min, salary_max, salary_currency, source_name, posted_at, first_seen_at)
VALUES
  -- ═══════════════════════════════════════════════════════════
  -- YOUTH AMBASSADOR PROGRAMMES
  -- ═══════════════════════════════════════════════════════════

  (
    'opp-caricome-youth-ambassador-2025-2027',
    'CARICOM Youth Ambassador Programme (CYAP) 2025-2027',
    'CARICOM',
    'CARICOM-wide',
    'Volunteer (unpaid)',
    'https://caricom.org/category/caricom-youth-ambassadors/',
    'Ages 15-30',
    'None — youth leadership interest',
    'ambassador',
    'CARICOM Youth Ambassador Programme representing Caribbean youth across the region. Ambassadors advocate for youth development, participate in regional meetings, and lead community projects. Applications typically open annually through National Youth Councils.',
    NULL,
    NULL,
    NULL,
    'curated',
    NOW(),
    NOW()
  ),
  (
    'opp-us-youth-ambassadors-caribbean',
    'U.S. Youth Ambassadors Program (Caribbean)',
    'U.S. Department of State / Georgetown University',
    'United States (for Caribbean secondary students)',
    'Fully funded (flights, accommodation, meals)',
    'https://exchanges.state.gov/non-us/program/youth-ambassadors',
    'Ages 15-18',
    'Must be secondary school student',
    'ambassador',
    'Fully funded exchange program bringing Caribbean secondary students to the United States for cultural immersion, leadership training, and community service. Applications accepted annually through U.S. Embassies in the Caribbean.',
    NULL,
    NULL,
    NULL,
    'curated',
    NOW(),
    NOW()
  ),
  (
    'opp-theirworld-global-youth-ambassador',
    'Theirworld Global Youth Ambassador Programme',
    'Theirworld',
    'Online / Global',
    'Volunteer (unpaid)',
    'https://theirworld.org/gyap-register-interest/',
    'Ages 18-30',
    'Passion for education and youth issues',
    'ambassador',
    'Global network of 2,000+ youth ambassadors advocating for every child''s right to education. Ambassadors receive training, networking opportunities, and support to run local campaigns. Applications open periodically — register interest for 2026 cycle.',
    NULL,
    NULL,
    NULL,
    'curated',
    NOW(),
    NOW()
  ),

  -- ═══════════════════════════════════════════════════════════
  -- SCHOLARSHIPS
  -- ═══════════════════════════════════════════════════════════

  (
    'opp-ccrif-scholarship-2026',
    'CCRIF Scholarship Programme 2026',
    'CCRIF SPC (Caribbean Catastrophe Risk Insurance Facility)',
    'CARICOM member countries',
    'Up to US$11,000 per scholarship',
    'https://www.ccrif.org/scholarship',
    'Ages 18+',
    'Enrolled or accepted into Masters/MBA programme',
    'scholarship',
    'Scholarships for Caribbean students pursuing Masters or MBA in disaster risk management, climate change, environmental management, or related fields. Over US$3 million invested in 200+ Caribbean youth to date. Deadline: June 14, 2026.',
    11000,
    11000,
    'USD',
    'curated',
    NOW(),
    NOW()
  ),
  (
    'opp-oas-academic-scholarship-caribbean',
    'OAS Academic Scholarships — Caribbean Undergraduate',
    'Organization of American States (OAS)',
    'OAS member states (English-speaking Caribbean & Suriname)',
    'Partial to full tuition',
    'https://www.oas.org/en/scholarships/',
    'Ages 18+',
    'Enrolled in undergraduate programme',
    'scholarship',
    'The OAS Academic Scholarships Program provides financial assistance to students of English-speaking Caribbean countries and Suriname for undergraduate studies. Applications typically open in April with a May 31 deadline.',
    NULL,
    NULL,
    NULL,
    'curated',
    NOW(),
    NOW()
  ),
  (
    'opp-carreras-scholarship-2026',
    'Carreras Scholarship Programme 2026',
    'Carreras Limited',
    'Jamaica',
    'Variable scholarship amount',
    'https://carreras-bat.vercel.app/',
    'Ages 18+',
    'Jamaican citizen, exemplary academic record',
    'scholarship',
    'Merit-based scholarship for Jamaican citizens aged 18+ with strong academic records. Application deadline: July 1, 2026 at 6:00 PM. Successful applicants receive tuition assistance for university studies.',
    NULL,
    NULL,
    'JMD',
    'curated',
    NOW(),
    NOW()
  ),
  (
    'opp-caribbean-science-foundation-scholarship',
    'Caribbean Science Foundation Scholarships',
    'Caribbean Science Foundation',
    'CARICOM-wide',
    'Variable',
    'https://caribbeanscience.org/scholarships/',
    'Ages 18+',
    'Enrolled in STEM programme at UWI or regional university',
    'scholarship',
    'Scholarships for Caribbean students pursuing STEM degrees at the University of the West Indies and other regional institutions. Supports undergraduate and graduate students in science, technology, engineering, and mathematics.',
    NULL,
    NULL,
    NULL,
    'curated',
    NOW(),
    NOW()
  ),
  (
    'opp-west-indian-foundation-scholarships',
    'West Indian Foundation Scholarships',
    'West Indian Foundation',
    'CARICOM-wide (diaspora eligible)',
    'Variable',
    'https://www.westindianfoundation.org/scholarships',
    'Ages 18+',
    'Strong academic record, community involvement',
    'scholarship',
    'Marcus Garvey and other scholarship programmes encouraging Caribbean students to reach higher standards of achievement. Available to Caribbean nationals and diaspora members pursuing higher education.',
    NULL,
    NULL,
    NULL,
    'curated',
    NOW(),
    NOW()
  ),
  (
    'opp-caribbean-maritime-foundation-scholarship',
    'American Caribbean Maritime Foundation Scholarship',
    'American Caribbean Maritime Foundation',
    'CARICOM-wide',
    'Up to US$3,375 per student (US$432,000 total pool)',
    'https://www.facebook.com/fb-answers/need-based-scholarships-for-caribbean-students/',
    'Ages 18+',
    'Enrolled in maritime or related programme',
    'scholarship',
    'Over US$432,000 in scholarships and grants awarded to 128 Caribbean students for 2025-2026. Supports students pursuing careers in the maritime industry including shipping, port management, and marine engineering.',
    3375,
    3375,
    'USD',
    'curated',
    NOW(),
    NOW()
  ),
  (
    'opp-google-generation-scholarship-caribbean',
    'Google Generation Scholarship (Caribbean)',
    'Google',
    'Remote / Caribbean',
    'US$10,000',
    'https://buildyourfuture.withgoogle.com/scholarships',
    'University students in STEM',
    'Enrolled in CS or related field, underrepresented in tech',
    'scholarship',
    'Google scholarship for students from underrepresented groups studying computer science or related fields. Includes a $10,000 award and invitation to a Google retreat. Applications typically open in the fall.',
    10000,
    10000,
    'USD',
    'curated',
    NOW(),
    NOW()
  ),
  (
    'opp-chevening-scholarship-caribbean',
    'Chevening Scholarship (Caribbean)',
    'UK Government',
    'UK (for Caribbean nationals)',
    'Full funding for UK Master''s degree',
    'https://chevening.org',
    'Ages 18+',
    'Bachelor''s degree, 2+ years work experience',
    'scholarship',
    'Prestigious UK government scholarship for Caribbean professionals. Covers tuition, living expenses, and travel for a one-year Master''s degree at any UK university. Applications open annually in August with a November deadline.',
    NULL,
    NULL,
    NULL,
    'curated',
    NOW(),
    NOW()
  ),

  -- ═══════════════════════════════════════════════════════════
  -- INTERNSHIPS & ON-THE-JOB TRAINING
  -- ═══════════════════════════════════════════════════════════

  (
    'opp-ccrif-internship-2026',
    'CCRIF SPC Internship Programme 2026',
    'CCRIF SPC',
    'CARICOM member countries (virtual/in-person)',
    'Paid internship',
    'https://www.ccrif.org/regional-internship-programme',
    'Ages 18-30',
    'University graduate or current student in relevant field',
    'internship',
    'Internship programme for young Caribbean professionals. Must be citizens of CARICOM or CCRIF member countries. Opportunities in risk management, climate finance, data analytics, and policy. Part of CCRIF''s US$3M+ investment in Caribbean youth.',
    NULL,
    NULL,
    NULL,
    'curated',
    NOW(),
    NOW()
  ),
  (
    'opp-royal-caribbean-internship-2026',
    'Royal Caribbean Group Summer Internship 2026',
    'Royal Caribbean Group',
    'Miami, Florida (HQ)',
    'Paid (10-week programme)',
    'https://careers.royalcaribbeangroup.com/careers/students/',
    'University students',
    'Actively enrolled in university programme',
    'internship',
    'Competitive 10-week summer internship at Royal Caribbean Group HQ in Miami. Gain hands-on experience across cruise operations, marketing, technology, finance, and more. Applications typically open in August-September.',
    NULL,
    NULL,
    'USD',
    'curated',
    NOW(),
    NOW()
  ),
  (
    'opp-carnival-early-talent-internship',
    'Carnival Corporation Early Talent Programme',
    'Carnival Corporation',
    'Miami, Florida',
    'Paid summer internship',
    'https://jobs.carnival.com/early-talent',
    'University students',
    'Actively enrolled in university',
    'internship',
    'Award-winning 10-week summer internship programme at Carnival Corporation. Provides meaningful work experience across the world''s largest cruise company. Multiple departments including technology, hospitality, and operations.',
    NULL,
    NULL,
    'USD',
    'curated',
    NOW(),
    NOW()
  ),
  (
    'opp-cimh-coding-classes-caribbean',
    'CIMH Caribbean Coding Classes',
    'Caribbean Institute for Meteorology and Hydrology (CIMH)',
    'Barbados, Jamaica, Trinidad & Tobago + 4 more Caribbean nations',
    'Free',
    'https://www.facebook.com/CIMHbb/',
    'Youth ages 13+',
    'None — beginners welcome',
    'training',
    'Free coding classes covering programming, robotics, artificial intelligence, and technology applications. Launched in 2025, now reaching seven Caribbean nations: Jamaica, Barbados, Trinidad & Tobago, and more. Part of CIMH''s youth training initiatives.',
    NULL,
    NULL,
    NULL,
    'curated',
    NOW(),
    NOW()
  ),
  (
    'opp-c3w-coding-workshop-2026',
    'Caribbean Computer Coding Workshops (C3W) 2026',
    'Caribbean Science Foundation',
    'Online / Caribbean',
    'Free',
    'https://caribbeanscience.org/coding-workshop/',
    'Ages 13+ (must be 13 by July 1st)',
    'None — beginners welcome',
    'training',
    'Summer 2026 coding workshops for Caribbean youth. Learn computer science fundamentals, programming, and computational thinking. Free to all accepted applicants. Application deadline typically in spring.',
    NULL,
    NULL,
    NULL,
    'curated',
    NOW(),
    NOW()
  ),
  (
    'opp-coding-for-caribbean-fellowship',
    'Code for the Caribbean Fellowship',
    'Code for the Caribbean',
    'Caribbean (various countries)',
    'Fellowship stipend',
    'https://codeforthecaribbean.org',
    'Ages 18-30',
    'Basic coding skills',
    'training',
    'Fellowship placing developers with Caribbean government agencies to build technology solutions for civic challenges. Stipend provided. Ideal for developers who want to use tech for public good across the Caribbean.',
    NULL,
    NULL,
    NULL,
    'curated',
    NOW(),
    NOW()
  ),

  -- ═══════════════════════════════════════════════════════════
  -- COMPETITIONS & HACKATHONS
  -- ═══════════════════════════════════════════════════════════

  (
    'opp-caribbean-ai-summit-hackathon-2026',
    'Caribbean AI Summit Hackathon 2026',
    'Caribbean AI Summit',
    'Caribbean (hybrid)',
    'Prizes + networking',
    'https://www.caribbeansummit.ai/en/hackathon',
    'Ages 18+',
    'Interest in AI/ML',
    'competition',
    '48-hour hackathon to build AI solutions for Caribbean challenges. Part of the Caribbean AI Summit 2026. October 9-10, 2026. Waitlist open — email caribbeanaisummit@gmail.com for participation.',
    NULL,
    NULL,
    NULL,
    'curated',
    NOW(),
    NOW()
  ),
  (
    'opp-caribbean-climate-tech-hackathon',
    'Caribbean Climate & Tech Hackathon',
    'Caribbean Climate Justice Alliance',
    'Caribbean',
    'Free to enter',
    'https://www.caribbeanclimatejustice.org/hackathon',
    'Ages 16-30',
    'Interest in climate/tech solutions',
    'competition',
    'Build tech-based solutions (IoT, sensors) to address Caribbean climate challenges. Hands-on opportunity for Caribbean youth to develop practical climate tech solutions. Mentoring and workshops included.',
    NULL,
    NULL,
    NULL,
    'curated',
    NOW(),
    NOW()
  ),
  (
    'opp-trinbago-tech-hackathon-2026',
    'Trinbago Tech Hackathon 2026',
    'CARIRI (Caribbean Industrial Research Institute)',
    'Trinidad and Tobago',
    'Prizes + networking',
    'https://www.facebook.com/caribbeanindustrialresearchinstitute/',
    'Ages 18+',
    'Interest in technology',
    'competition',
    'Tech hackathon organized by CARIRI bringing together innovators across Trinidad and Tobago. Prize-giving and networking events. Contact jramoutar@cariri.com for details.',
    NULL,
    NULL,
    'TTD',
    'curated',
    NOW(),
    NOW()
  ),
  (
    'opp-intellibus-hackathon-2027',
    'Intellibus Hackathon 2027',
    'Intellibus',
    'Caribbean (in-person)',
    'Prizes',
    'https://www.intellibushackathon.com/',
    'Ages 18+',
    'Interest in AI/tech',
    'competition',
    'Caribbean''s largest in-person hackathon. Registration open for January 2027. Build, innovate, and compete. Focus on AI and emerging technology solutions.',
    NULL,
    NULL,
    NULL,
    'curated',
    NOW(),
    NOW()
  ),
  (
    'opp-jamaica-logistics-hackathon-2026',
    'Jamaica Island Logistics Hackathon 2026',
    'Tech Community Jamaica',
    'Jamaica (The Hub CoWorking, New Kingston)',
    '1st: $50,000 JMD | 2nd: $30,000 JMD | 3rd: $15,000 JMD',
    'https://www.instagram.com/p/DVmMZ9AAnaX/',
    'Ages 16+',
    'Interest in tech/logistics',
    'competition',
    'Jamaica''s biggest tech opportunity. Theme: Island Logistics. Date: July 11, 2026 at The Hub CoWorking, New Kingston. Prize pool includes cash awards and a Freshest Fit Award.',
    15000,
    50000,
    'JMD',
    'curated',
    NOW(),
    NOW()
  ),
  (
    'opp-ieee-rising-stars-hackathon-2026',
    'IEEE Rising Stars Latin America & Caribbean Hackathon 2026',
    'IEEE',
    'Latin America & Caribbean (hybrid)',
    'Free to enter',
    'https://r9.ieee.org/sac/event/attendance-at-the-hackathon-of-the-ieee-rising-stars-latin-america-and-caribbean-conference-2026-event-and-participation-in-the-rising-stars-hackathon-copa-aws/',
    'Ages 18+',
    'Interest in engineering/tech',
    'competition',
    'Hackathon at the IEEE Rising Stars Latin America & Caribbean Conference. September 4-6, 2026. Includes Copa AWS collaboration. Network with IEEE professionals and build innovative solutions.',
    NULL,
    NULL,
    NULL,
    'curated',
    NOW(),
    NOW()
  ),
  (
    'opp-future-caribbean-ai-buildathon',
    'Future Caribbean AI Buildathon',
    'Future Caribbean',
    'Online / Global',
    'Free to enter',
    'https://futurecaribbean.com/',
    'Ages 18+',
    'Interest in AI and economic development',
    'competition',
    'Global agentic AI buildathon creating deployable solutions that strengthen how economies coordinate — from the Caribbean to the world. Community-driven, open to all skill levels.',
    NULL,
    NULL,
    NULL,
    'curated',
    NOW(),
    NOW()
  ),

  -- ═══════════════════════════════════════════════════════════
  -- VOLUNTEER & COMMUNITY SERVICE
  -- ═══════════════════════════════════════════════════════════

  (
    'opp-ivhq-caribbean-volunteer',
    'IVHQ Caribbean Volunteer Programmes',
    'International Volunteer HQ (IVHQ)',
    'Belize, Jamaica, Puerto Rico, Dominican Republic',
    'Programme fees from ~$300/week',
    'https://www.volunteerhq.org/regions/caribbean/',
    'Ages 18+',
    'None',
    'volunteer',
    'Best-rated Caribbean volunteer programmes including Marine Conservation in Belize, Teaching in Jamaica, and Community Development in Puerto Rico. Accommodation and meals typically included. Multiple start dates year-round.',
    NULL,
    NULL,
    NULL,
    'curated',
    NOW(),
    NOW()
  ),
  (
    'opp-barbados-summer-camp-volunteer-2026',
    'Barbados National Summer Camp Programme 2026 — Volunteer',
    'Barbados Division of Youth Affairs',
    'Barbados',
    'Volunteer (unpaid)',
    'https://www.facebook.com/divisionofyouthbarbados/',
    'Ages 16+',
    'Interest in youth development',
    'volunteer',
    'Volunteer for the Barbados National Summer Camp Programme 2026. Help run summer activities for young Barbadians. Application deadline: Sunday, June 29, 2026. Contact: 535-xxxx.',
    NULL,
    NULL,
    NULL,
    'curated',
    NOW(),
    NOW()
  ),
  (
    'opp-un-volunteer-caribbean',
    'UNV Online Volunteer — Caribbean',
    'United Nations Volunteers',
    'Remote (global)',
    'Volunteer (unpaid)',
    'https://onlinevolunteering.org',
    'Ages 18+',
    'Skills-based volunteering available',
    'volunteer',
    'Online volunteering with UN agencies. Skills-based opportunities in translation, web development, graphic design, research, and more. Available to Caribbean nationals. Flexible schedule.',
    NULL,
    NULL,
    NULL,
    'curated',
    NOW(),
    NOW()
  ),
  (
    'opp-peace-corps-caribbean',
    'Peace Corps Caribbean',
    'Peace Corps',
    'Dominican Republic, Jamaica, Guyana',
    'Living stipend + readjustment allowance',
    'https://peacecorps.gov',
    'Ages 18-34',
    'Bachelor''s degree preferred',
    'volunteer',
    'Peace Corps service in Caribbean countries. 27-month commitment including community development, education, health, and environment projects. Living stipend, housing, and readjustment allowance provided.',
    NULL,
    NULL,
    NULL,
    'curated',
    NOW(),
    NOW()
  ),
  (
    'opp-amigos-caribbean-teens',
    'AMIGOS Volunteer & Leadership — Latin America & Caribbean',
    'AMIGOS de las Américas',
    'Latin America & Caribbean',
    'Programme fees apply (scholarships available)',
    'https://amigosinternational.org/',
    'Ages 15-19',
    'None — leadership training provided',
    'volunteer',
    '60 years of youth leadership development. Volunteer and immersion programs for teens in Latin America and the Caribbean. Includes host families, community-driven service, and leadership training. Scholarships available.',
    NULL,
    NULL,
    NULL,
    'curated',
    NOW(),
    NOW()
  ),
  (
    'opp-habitat-humanity-caribbean',
    'Habitat for Humanity Global Village — Caribbean',
    'Habitat for Humanity',
    'Various Caribbean countries',
    'Trip costs (fundraising supported)',
    'https://www.habitat.org/stories/service-opportunities-teens',
    'Ages 16+',
    'None',
    'volunteer',
    'Join Habitat for Humanity Global Village trips to build homes in Caribbean communities. Teens 16+ welcome. Trip costs can be offset through personal fundraising. Multiple destinations across the Caribbean year-round.',
    NULL,
    NULL,
    NULL,
    'curated',
    NOW(),
    NOW()
  ),

  -- ═══════════════════════════════════════════════════════════
  -- FOUNDATIONS & ORGANIZATIONS
  -- ═══════════════════════════════════════════════════════════

  (
    'opp-willow-foundation-tt',
    'Willow Foundation Trinidad & Tobago',
    'Willow Foundation',
    'Trinidad and Tobago',
    'Free — education & outreach programmes',
    'https://www.facebook.com/thewillowfoundationtt/',
    'All ages',
    'None',
    'club',
    'Trinidad & Tobago-based foundation providing education, humanitarian resources, outreach programmes, and refuge services for young persons and senior citizens. Community support and development initiatives.',
    NULL,
    NULL,
    NULL,
    'curated',
    NOW(),
    NOW()
  ),
  (
    'opp-digicel-bright-stars',
    'Digicel Foundation Bright Stars Challenge',
    'Digicel Foundation',
    'CARICOM-wide',
    'Funding for winning projects',
    'https://digicelfoundation.com',
    'Ages 15-25',
    'Social impact project idea',
    'competition',
    'Youth entrepreneurship challenge supporting social impact projects across the Caribbean. Winning teams receive funding and mentorship to bring their community-focused projects to life.',
    NULL,
    NULL,
    NULL,
    'curated',
    NOW(),
    NOW()
  ),
  (
    'opp-ccrif-small-grants-2026',
    'CCRIF Small Grants Programme 2026',
    'CCRIF SPC',
    'CARICOM member countries',
    'US$5,000 to US$25,000',
    'https://www.ccrif.org/scholarship',
    'Youth organisations (ages 11-20)',
    'Community-based organisation working with rural youth',
    'grant',
    'Small grants of US$5,000 to US$25,000 for community organisations working with rural youth (ages 11-20) and children (ages 5-15) on disaster preparedness, climate resilience, and community development.',
    5000,
    25000,
    'USD',
    'curated',
    NOW(),
    NOW()
  ),
  (
    'opp-who-internship-caribbean',
    'WHO Internship Programme (Eastern Caribbean)',
    'World Health Organization',
    'Eastern Caribbean (PAHO/WHO office)',
    'Stipend (varies)',
    'https://www.who.int/about/who-internship-programme',
    'Ages 20+',
    'Currently enrolled or recently graduated university student',
    'internship',
    'WHO internship opportunities through the Pan American Health Organization (PAHO) Eastern Caribbean offices. Gain experience in public health, epidemiology, health policy, and programme management.',
    NULL,
    NULL,
    NULL,
    'curated',
    NOW(),
    NOW()
  )
ON CONFLICT (id) DO NOTHING;
