'use client'

import { useState, useEffect } from 'react'
import { Map } from 'lucide-react'
import AppLayout from '@/components/AppLayout'
import { supabase } from '@/lib/supabase'

export default function RoadmapPage() {
  const [userName, setUserName] = useState('')

  useEffect(() => {
    const load = async () => {
      const { data: { user } } = await supabase.auth.getUser()
      if (user) {
        const { data } = await supabase.from('users').select('name').eq('id', user.id).single()
        if (data?.name) setUserName(data.name)
      }
    }
    load()
  }, [])

  return (
    <AppLayout>
      <div className="flex h-screen bg-[#F9F5FF]">
        <div className="flex-1 flex items-center justify-center">
          <div className="text-center max-w-md">
            <div className="w-16 h-16 rounded-full bg-[#EADFFF] flex items-center justify-center mx-auto mb-4">
              <Map size={24} className="text-[#6B26EA]" />
            </div>
            <p className="text-lg font-semibold text-[#0D0026] mb-2" style={{ fontFamily: "'Bricolage Grotesque', sans-serif" }}>
              {userName ? `Welcome, ${userName}` : 'Your Roadmap'}
            </p>
            <p className="text-sm text-[#8B898E]" style={{ fontFamily: "'Inter', sans-serif" }}>
              Your personalized career roadmap will appear here once generated by LYNKS AI.
            </p>
          </div>
        </div>
      </div>
    </AppLayout>
  )
}
